export const GAME_PHASES = [
  "LOBBY",
  "CARD_PICKING",
  "ROLE_REVEAL",
  "NIGHT_START",
  "NIGHT_GUARD",
  "NIGHT_WEREWOLF",
  "NIGHT_SEER",
  "NIGHT_WITCH",
  "DAY_ANNOUNCEMENT",
  "HUNTER_SHOOT",
  "DAY_DISCUSSION",
  "DAY_VOTE",
  "DAY_TIEBREAK_DISCUSSION",
  "DAY_EXILE_RESULT",
  "DAY_LAST_WORDS",
  "GAME_OVER",
] as const;

export type GamePhase = (typeof GAME_PHASES)[number];
